name: build-tag-publish ESP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-tag-publish:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Generate a Timestamp for the Version
      - name: Generate Version
        id: generate_version
        run: |
          $timestamp = Get-Date -Format "yyyyMMdd-HHmm"
          echo "version=V$timestamp" >> $env:GITHUB_ENV
        shell: pwsh

      # Configure the project
      - name: Configure Project
        run: cmake -B build -S .

      # Build the project
      - name: Build Project
        run: cmake --build build --config Release

      # Zip the executable file
      - name: Zip Executable
        run: |
          Compress-Archive -Path build/ESP-MID/* -Destination build/ESP-MID/ESP.zip
          
      # Upload Build Artifact
      - name: Upload Zipped Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ESP-Zipped
          path: build/ESP-MID/ESP.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.version }} # Use the dynamically generated tag
          release_name: Release ${{ env.version }} # Use the dynamic tag for the release name
          body: |
            **What's New:**
            - ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      # Upload Artifact to Release
      - name: Upload Zipped File to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/ESP-MID/ESP.zip
          asset_name: ESP.zip
          asset_content_type: application/zip
